name: Build Kivy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git libncurses5:i386 libstdc++6:i386 zlib1g:i386 unzip ant openjdk-8-jdk
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build the Kivy app
      run: |
        buildozer android debug
